-- RLS PostgreSQL — ACTIVÉ via migration 20260717220000_enable_rls_tenant_isolation.
--
-- Variables de session (RlsContextInterceptor) :
--   app.organization_id, app.user_id, app.is_main, app.rls_bypass
--
-- Important : utiliser une connexion Postgres directe (pas PgBouncer en mode
-- transaction). Le seeder et les crons posent app.rls_bypass=on.
--
-- Table User : volontairement hors RLS (login / résolution JWT avant contexte).
