/**
 * Liste alignée sur `docs/PERMISSIONS-CASL.md` (section « Liste plate »).
 * Utilisée par le seeder pour garantir que toutes les permissions CASL existent en base.
 */
export const CASL_SEED_PERMISSION_NAMES = [
  'read:User',
  'create:User',
  'update:User',
  'delete:User',
  'read:Organization',
  'create:Organization',
  'update:Organization',
  'delete:Organization',
  'read:Role',
  'create:Role',
  'update:Role',
  'delete:Role',
  'read:Pole',
  'create:Pole',
  'update:Pole',
  'delete:Pole',
  'read:Permission',
  'create:Permission',
  'update:Permission',
  'delete:Permission',
  'read:AuditLog',
  'read:LoginAttempt',
  'read:Category',
  'create:Category',
  'update:Category',
  'delete:Category',
  'read:Product',
  'create:Product',
  'update:Product',
  'delete:Product',
  'read:Stock',
  'create:Stock',
  'update:Stock',
  'delete:Stock',
  'read:StockOrder',
  'create:StockOrder',
  'update:StockOrder',
  'delete:StockOrder',
  'read:Vente',
  'create:Vente',
  'update:Vente',
  'delete:Vente',
  'read:SessionCaisse',
  'create:SessionCaisse',
  'update:SessionCaisse',
  'read:StockMovement',
  'read:StockTransfer',
  'create:StockTransfer',
  'update:StockTransfer',
  'delete:StockTransfer',
  'read:HeritageAsset',
  'create:HeritageAsset',
  'update:HeritageAsset',
  'delete:HeritageAsset',
  'read:LegalContract',
  'create:LegalContract',
  'update:LegalContract',
  'delete:LegalContract',
  'read:ProductionOrder',
  'create:ProductionOrder',
  'update:ProductionOrder',
  'delete:ProductionOrder',
  'read:AccountingPeriod',
  'manage:AccountingPeriod',
  'read:Notification',
  'update:Notification',
  'read:Message',
  'create:Message',
  'update:Message',
  'read:Task',
  'create:Task',
  'update:Task',
  'delete:Task',
  'read:Supplier',
  'create:Supplier',
  'update:Supplier',
  'delete:Supplier',
  'read:Budget',
  'create:Budget',
  'update:Budget',
  'delete:Budget',
  'read:BudgetExpense',
  'create:BudgetExpense',
  'update:BudgetExpense',
  'delete:BudgetExpense',
  'read:BudgetSupplementRequest',
  'create:BudgetSupplementRequest',
  'update:BudgetSupplementRequest',
  'delete:BudgetSupplementRequest',
  'read:Department',
  'create:Department',
  'update:Department',
  'delete:Department',
  'read:Employee',
  'create:Employee',
  'update:Employee',
  'delete:Employee',
  'read:LeaveRequest',
  'create:LeaveRequest',
  'update:LeaveRequest',
  'delete:LeaveRequest',
  'read:LeaveBalance',
  'create:LeaveBalance',
  'update:LeaveBalance',
  'delete:LeaveBalance',
  'read:EmploymentContract',
  'create:EmploymentContract',
  'update:EmploymentContract',
  'delete:EmploymentContract',
  'read:EmployeeSalary',
  'create:EmployeeSalary',
  'update:EmployeeSalary',
  'delete:EmployeeSalary',
  'read:WorkShift',
  'create:WorkShift',
  'update:WorkShift',
  'delete:WorkShift',
  'read:EmployeeSanction',
  'create:EmployeeSanction',
  'update:EmployeeSanction',
  'delete:EmployeeSanction',
  'read:EmployeeDeparture',
  'create:EmployeeDeparture',
  'update:EmployeeDeparture',
  'delete:EmployeeDeparture',
  'read:all',
  'manage:all',
] as const;

const ACTION_LABEL: Record<string, string> = {
  read: 'Lecture',
  create: 'Création',
  update: 'Modification',
  delete: 'Suppression',
  manage: 'Gestion complète',
};

/** Libellé court pour la colonne `Permission.description`. */
export function describeCaslPermission(name: string): string {
  if (name === 'read:all') {
    return 'Lecture sur tous les modules (wildcard CASL)';
  }
  if (name === 'manage:all') {
    return 'Gestion complète sur tous les modules (wildcard CASL)';
  }
  const idx = name.indexOf(':');
  if (idx <= 0) {
    return name;
  }
  const action = name.slice(0, idx).toLowerCase();
  const subject = name.slice(idx + 1);
  const actionFr = ACTION_LABEL[action] ?? action;
  return `${actionFr} — ${subject}`;
}
